+ gather()
+ spread()
+ unite()

In [49]:
library(tidyr)
library(dplyr)

+ key 的命名轉成長數據欄位 , value 欄位命名

In [44]:
stocks <- data.frame(
  time = as.Date('2009-01-01') + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4)
)
stocks

   time       X           Y          Z
1  2009-01-01 -0.62118219  0.6120451   5.27521350
2  2009-01-02 -0.67736990  1.7597013  -0.09141865
3  2009-01-03  0.44324976 -0.9494451   2.35238012
4  2009-01-04  0.58184546 -1.2526869  -7.56601935
5  2009-01-05 -0.06912637  1.2146123  -6.06754642
6  2009-01-06  0.81964341 -1.3802760   2.56598350
7  2009-01-07 -0.16272483 -0.3689875  -2.94783877
8  2009-01-08 -0.04577992  2.0086345  -7.52694475
9  2009-01-09  0.18457431 -1.8286522  -1.87902739
10 2009-01-10 -1.41949819 -0.7528809 -11.41931938

In [50]:
stocksm <- stocks %>% gather(stock, price, -time)
stocksm[1:3,]

  time       stock price
1 2009-01-01 X     -0.6211822
2 2009-01-02 X     -0.6773699
3 2009-01-03 X      0.4432498

In [48]:
stocksm %>% spread(stock, price)

   time       X           Y          Z
1  2009-01-01 -0.62118219  0.6120451   5.27521350
2  2009-01-02 -0.67736990  1.7597013  -0.09141865
3  2009-01-03  0.44324976 -0.9494451   2.35238012
4  2009-01-04  0.58184546 -1.2526869  -7.56601935
5  2009-01-05 -0.06912637  1.2146123  -6.06754642
6  2009-01-06  0.81964341 -1.3802760   2.56598350
7  2009-01-07 -0.16272483 -0.3689875  -2.94783877
8  2009-01-08 -0.04577992  2.0086345  -7.52694475
9  2009-01-09  0.18457431 -1.8286522  -1.87902739
10 2009-01-10 -1.41949819 -0.7528809 -11.41931938